// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// generate.go — parses the control-api action registry with go/parser, walks
// the registry composite literal with go/ast, and renders the HTTP surface as
// grouped markdown tables. Stdlib only; no new dependencies.
//
// Source of truth: `lib/control/controlapi/actions.go`, which declares
//
//	type ActionEntry struct { Action string; IsWrite bool; Routes []Route; ... }
//	type Route struct { Method string; Path string }
//	var v1Actions = []ActionEntry{ {Action: ..., Routes: []Route{{"GET", "/x"}}, ...}, ... }
//
// Each route's auth gate is the entry's action string itself (the auth
// middleware maps METHOD+pattern → action and gates it); IsWrite distinguishes
// a read action from a write action.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const autogenBanner = "<!-- AUTOGENERATED by rimsky-docs-rest-ref from rimsky lib/control/controlapi/actions.go. Do not hand-edit. -->"

// registryVar is the name of the canonical action-registry slice in actions.go.
const registryVar = "v1Actions"

// route is one HTTP method+path pair and the action that gates it.
type route struct {
	Method      string
	Path        string
	Action      string
	IsWrite     bool
	Description string
}

// run renders the REST API reference from actionsFile to outPath. With
// check=true, compare against disk and error on drift.
func run(actionsFile, outPath string, check bool) error {
	md, err := renderReference(actionsFile)
	if err != nil {
		return err
	}

	if check {
		want, err := os.ReadFile(outPath)
		if err != nil || !bytes.Equal([]byte(md), want) {
			return fmt.Errorf("REST API reference is out of date for:\n  %s\nrun `go run ./cmd/rimsky-docs-rest-ref` to regenerate", outPath)
		}
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(md), 0644)
}

// renderReference parses the action registry and renders the full markdown doc.
func renderReference(actionsFile string) (string, error) {
	routes, err := parseRoutes(actionsFile)
	if err != nil {
		return "", err
	}
	if len(routes) == 0 {
		return "", fmt.Errorf("%s: no routes found in %s registry; did the registry shape change?", actionsFile, registryVar)
	}

	groups := groupByPrefix(routes)
	actionCount := countActions(routes)

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", autogenBanner)
	fmt.Fprintf(&b, "# REST / HTTP control API reference\n\n")
	fmt.Fprintf(&b, "Complete route table for rimsky's HTTP+JSON control API, generated from "+
		"the canonical action registry (`lib/control/controlapi/actions.go`). Every "+
		"route below is also reachable as an MCP tool over the same auth gate; this "+
		"page lists the HTTP surface only.\n\n")
	fmt.Fprintf(&b, "- **Bare, unversioned paths.** V1 does not version the wire format; "+
		"rolling upgrades are operator-managed (see `concept:control-api`).\n")
	fmt.Fprintf(&b, "- **Every route is auth-gated per-action.** The registry is the canonical "+
		"route → action mapping. The auth + permission middleware resolves an incoming "+
		"`METHOD` + routed pattern to its **auth gate** (the action string in the table) "+
		"and checks it against the requesting key's grant; an unmapped route is a wiring "+
		"bug. The only ungated routes are the health and readiness probes, which are not "+
		"in the registry and so do not appear below.\n")
	fmt.Fprintf(&b, "- **R/W** marks whether the gate is a read action (`false`) or a write "+
		"action (`true`); bundled `*:read` roles cover every read gate.\n\n")
	fmt.Fprintf(&b, "%d routes across %d actions.\n\n", len(routes), actionCount)

	for _, g := range groups {
		fmt.Fprintf(&b, "## %s\n\n", g.Title)
		fmt.Fprintf(&b, "| Method | Path | Auth gate | R/W | Action |\n")
		fmt.Fprintf(&b, "| --- | --- | --- | --- | --- |\n")
		for _, r := range g.Routes {
			fmt.Fprintf(&b, "| `%s` | `%s` | `%s` | %s | %s |\n",
				r.Method, r.Path, r.Action, rwLabel(r.IsWrite), escapeCell(r.Description))
		}
		b.WriteString("\n")
	}
	return b.String(), nil
}

func rwLabel(isWrite bool) string {
	if isWrite {
		return "W"
	}
	return "R"
}

// escapeCell makes a free-text action description safe inside a markdown table
// cell. Descriptions are rendered verbatim apart from pipe escaping.
func escapeCell(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// group is a set of routes sharing a resource prefix.
type group struct {
	Title  string
	Routes []route
}

// groupByPrefix buckets routes by their leading path segment (or the segment
// after a /admin or /v1 prefix), then sorts both groups and the routes inside
// each group deterministically so -check is stable.
func groupByPrefix(routes []route) []group {
	buckets := map[string][]route{}
	for _, r := range routes {
		key := prefixOf(r.Path)
		buckets[key] = append(buckets[key], r)
	}

	titles := make([]string, 0, len(buckets))
	for k := range buckets {
		titles = append(titles, k)
	}
	sort.Strings(titles)

	out := make([]group, 0, len(buckets))
	for _, t := range titles {
		rs := buckets[t]
		sort.Slice(rs, func(i, j int) bool {
			if rs[i].Path != rs[j].Path {
				return rs[i].Path < rs[j].Path
			}
			if rs[i].Method != rs[j].Method {
				return methodRank(rs[i].Method) < methodRank(rs[j].Method)
			}
			return rs[i].Action < rs[j].Action
		})
		out = append(out, group{Title: t, Routes: rs})
	}
	return out
}

// prefixOf returns the human-facing group title for a route path. Routes under
// /admin or /v1 are grouped under those operator/observability prefixes;
// everything else groups by its first path segment.
func prefixOf(path string) string {
	segs := pathSegments(path)
	if len(segs) == 0 {
		return "/"
	}
	switch segs[0] {
	case "admin":
		return "/admin"
	case "v1":
		return "/v1"
	default:
		return "/" + segs[0]
	}
}

// pathSegments splits a chi path into its literal/template segments, dropping
// the leading slash and any trailing empties.
func pathSegments(path string) []string {
	var out []string
	for _, s := range strings.Split(path, "/") {
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

// methodRank orders HTTP methods read-before-write for stable display.
func methodRank(m string) int {
	switch m {
	case "GET":
		return 0
	case "POST":
		return 1
	case "PUT":
		return 2
	case "PATCH":
		return 3
	case "DELETE":
		return 4
	default:
		return 5
	}
}

// countActions counts the distinct action strings across all routes.
func countActions(routes []route) int {
	seen := map[string]bool{}
	for _, r := range routes {
		seen[r.Action] = true
	}
	return len(seen)
}

// parseRoutes parses actionsFile and extracts every route from the registry
// slice literal. Each ActionEntry contributes one route per (method, path) pair
// in its Routes field; the entry's Action is the auth gate.
func parseRoutes(actionsFile string) ([]route, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, actionsFile, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", actionsFile, err)
	}

	consts, err := collectStringConsts(fset, actionsFile)
	if err != nil {
		return nil, err
	}

	lit := findRegistryLiteral(f)
	if lit == nil {
		return nil, fmt.Errorf("%s: could not find registry slice literal %q", actionsFile, registryVar)
	}

	var routes []route
	for _, elt := range lit.Elts {
		entry, ok := elt.(*ast.CompositeLit)
		if !ok {
			continue
		}
		action, isWrite, desc, rts := parseEntry(entry, consts)
		if action == "" {
			return nil, fmt.Errorf("%s: registry entry with no Action field", actionsFile)
		}
		for _, rt := range rts {
			routes = append(routes, route{
				Method:      rt.Method,
				Path:        rt.Path,
				Action:      action,
				IsWrite:     isWrite,
				Description: desc,
			})
		}
	}
	return routes, nil
}

// collectStringConsts walks every .go file in actionsFile's directory and
// returns a map of package-level string-typed const name → unquoted value.
// Registry entries may reference these constants instead of inline literals
// (e.g. `{Action: composeOriginAction, ...}` where the const lives in a
// sibling file).
func collectStringConsts(fset *token.FileSet, actionsFile string) (map[string]string, error) {
	dir := filepath.Dir(actionsFile)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read package dir %s: %w", dir, err)
	}
	out := map[string]string{}
	for _, ent := range entries {
		if ent.IsDir() || !strings.HasSuffix(ent.Name(), ".go") || strings.HasSuffix(ent.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(dir, ent.Name())
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, name := range vs.Names {
					if i >= len(vs.Values) {
						continue
					}
					if s := stringValue(vs.Values[i], nil); s != "" {
						out[name.Name] = s
					}
				}
			}
		}
	}
	return out, nil
}

// findRegistryLiteral locates the `var v1Actions = []ActionEntry{...}`
// declaration and returns its composite-literal value.
func findRegistryLiteral(f *ast.File) *ast.CompositeLit {
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if name.Name != registryVar || i >= len(vs.Values) {
					continue
				}
				if lit, ok := vs.Values[i].(*ast.CompositeLit); ok {
					return lit
				}
			}
		}
	}
	return nil
}

// rawRoute is a (method, path) pair pulled from a Routes literal.
type rawRoute struct {
	Method string
	Path   string
}

// parseEntry pulls the Action, IsWrite, Description, and Routes out of one
// ActionEntry composite literal. consts maps package-level string-const names
// to their values, so entries that name a const for Action (or Description)
// instead of an inline literal still resolve.
func parseEntry(entry *ast.CompositeLit, consts map[string]string) (action string, isWrite bool, desc string, routes []rawRoute) {
	for _, el := range entry.Elts {
		kv, ok := el.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Action":
			action = stringValue(kv.Value, consts)
		case "Description":
			desc = stringValue(kv.Value, consts)
		case "IsWrite":
			isWrite = boolValue(kv.Value)
		case "Routes":
			routes = parseRoutesField(kv.Value)
		}
	}
	return action, isWrite, desc, routes
}

// parseRoutesField extracts every {"METHOD", "/path"} pair from a
// `[]Route{...}` composite literal. Route literals only ever use string
// literals for method+path (never package-level consts), so no const map
// is needed here.
func parseRoutesField(v ast.Expr) []rawRoute {
	lit, ok := v.(*ast.CompositeLit)
	if !ok {
		return nil
	}
	var out []rawRoute
	for _, el := range lit.Elts {
		rl, ok := el.(*ast.CompositeLit)
		if !ok {
			continue
		}
		rt := parseRouteLiteral(rl)
		if rt.Method != "" && rt.Path != "" {
			out = append(out, rt)
		}
	}
	return out
}

// parseRouteLiteral reads one Route literal, supporting both positional
// (`{"GET", "/x"}`) and keyed (`{Method: "GET", Path: "/x"}`) forms.
func parseRouteLiteral(rl *ast.CompositeLit) rawRoute {
	var rt rawRoute
	pos := 0
	for _, el := range rl.Elts {
		if kv, ok := el.(*ast.KeyValueExpr); ok {
			if key, ok := kv.Key.(*ast.Ident); ok {
				switch key.Name {
				case "Method":
					rt.Method = stringValue(kv.Value, nil)
				case "Path":
					rt.Path = stringValue(kv.Value, nil)
				}
			}
			continue
		}
		switch pos {
		case 0:
			rt.Method = stringValue(el, nil)
		case 1:
			rt.Path = stringValue(el, nil)
		}
		pos++
	}
	return rt
}

// stringValue returns the value of a string-literal expression, or "". If
// consts is non-nil and the expression is an identifier whose name is in the
// map, the const's value is returned — letting registry entries reference
// package-level string consts (e.g. `{Action: composeOriginAction}`) instead
// of inline literals.
func stringValue(e ast.Expr, consts map[string]string) string {
	if lit, ok := e.(*ast.BasicLit); ok && lit.Kind == token.STRING {
		s, err := strconv.Unquote(lit.Value)
		if err != nil {
			return ""
		}
		return s
	}
	if id, ok := e.(*ast.Ident); ok && consts != nil {
		return consts[id.Name]
	}
	return ""
}

// boolValue returns the value of a `true`/`false` identifier expression.
func boolValue(e ast.Expr) bool {
	id, ok := e.(*ast.Ident)
	return ok && id.Name == "true"
}
