// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// generate.go — parses the spec package with go/parser + go/doc and builds a
// flat model of its exported structs and enums. The model is rendered by
// render.go. Stdlib only; no new dependencies.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const autogenBanner = "<!-- AUTOGENERATED by rimsky-docs-template-ref from rimsky lib/foundation/spec/. Do not hand-edit. -->"

// run renders the template schema reference for specDir to outPath. With
// check=true, compare against disk and error on drift.
func run(specDir, outPath string, check bool) error {
	model, err := parseSpec(specDir)
	if err != nil {
		return err
	}
	md := renderReference(model)

	if check {
		want, err := os.ReadFile(outPath)
		if err != nil || !bytes.Equal([]byte(md), want) {
			return fmt.Errorf("template schema reference is out of date for:\n  %s\nrun `go run ./cmd/rimsky-docs-template-ref` to regenerate", outPath)
		}
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(md), 0644)
}

// specField is one struct field: the YAML key it parses from, the readable Go
// type, whether it carries omitempty/inline, and the field's doc comment.
//
// Tagged is true when the YAML key came from an explicit yaml:/json: tag
// (false when synthesized from the lowercased Go field name).
type specField struct {
	GoField   string
	YAMLKey   string
	GoType    string
	OmitEmpty bool
	Inline    bool
	Doc       string
	Tagged    bool
}

// specStruct is one exported struct in the spec package.
//
// Tagged reports whether any field carries a yaml: or json: tag. A struct with
// no tagged fields is a runtime-only / DB-projection type, not part of the
// template YAML — the renderer files those under a separate section so their
// (synthesized lowercase) field names are not mistaken for YAML keys.
type specStruct struct {
	Name   string
	Doc    string
	Fields []specField
	Tagged bool
}

// enumValue is one constant in an enum group: the Go const name, its literal
// value (best-effort; empty when not a string literal), and its doc.
type enumValue struct {
	Name  string
	Value string
	Doc   string
}

// specEnum is either a named string-typed enum (Typed=true, with the type's
// own doc) or a standalone const group keyed by a synthetic title.
type specEnum struct {
	Name   string // the Go type name, or a synthetic group title for untyped groups
	GoType string // underlying type ("string" for typed enums; "" for untyped groups)
	Typed  bool
	Doc    string
	Values []enumValue
}

// specModel is the flattened, rendering-ready view of the spec package.
type specModel struct {
	PackageDoc string
	Structs    map[string]*specStruct // keyed by type name
	StructList []string               // names in source order
	Enums      []*specEnum
	// structNames is the set of exported struct type names, used by the
	// renderer to decide which type references to cross-link.
	structNames map[string]bool
	enumNames   map[string]bool
}

// parseSpec parses every non-test .go file in specDir and builds the model.
func parseSpec(specDir string) (*specModel, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, specDir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", specDir, err)
	}
	if len(pkgs) == 0 {
		return nil, fmt.Errorf("no Go package found in %s", specDir)
	}

	m := &specModel{
		Structs:     map[string]*specStruct{},
		structNames: map[string]bool{},
		enumNames:   map[string]bool{},
	}

	for _, pkg := range pkgs {
		// go/doc gives us tidy, exported-only doc comments and the const
		// grouping; the raw AST gives us field tags and underlying type kinds.
		dpkg := doc.New(pkg, "spec", doc.AllDecls)
		m.PackageDoc = strings.TrimSpace(dpkg.Doc)
		collectTypes(m, dpkg, fset)
	}
	return m, nil
}

// collectTypes walks the go/doc types and pulls out exported structs and
// enums. Each doc.Type bundles the type's spec, its doc, and the const groups
// declared for it.
func collectTypes(m *specModel, dpkg *doc.Package, fset *token.FileSet) {
	// Typed enums + structs come from dpkg.Types. Standalone const groups
	// (untyped string sets like the node-state constants) come from
	// dpkg.Consts.
	for _, t := range dpkg.Types {
		if !ast.IsExported(t.Name) {
			continue
		}
		ts := typeSpecOf(t)
		if ts == nil {
			continue
		}
		switch underlying := ts.Type.(type) {
		case *ast.StructType:
			m.structNames[t.Name] = true
		case *ast.Ident:
			// A named type over a builtin (e.g. `type Severity string`). With
			// associated string consts, treat it as an enum.
			if underlying.Name == "string" && len(t.Consts) > 0 {
				m.enumNames[t.Name] = true
			}
		}
	}

	for _, t := range dpkg.Types {
		if !ast.IsExported(t.Name) {
			continue
		}
		ts := typeSpecOf(t)
		if ts == nil {
			continue
		}
		switch underlying := ts.Type.(type) {
		case *ast.StructType:
			s := buildStruct(m, t.Name, strings.TrimSpace(t.Doc), underlying, fset)
			m.Structs[t.Name] = s
			m.StructList = append(m.StructList, t.Name)
		case *ast.Ident:
			if underlying.Name == "string" && len(t.Consts) > 0 {
				m.Enums = append(m.Enums, buildTypedEnum(t))
			}
		}
	}

	// Standalone (untyped) const groups: const blocks whose type is not one of
	// the named enum types. These are the bare string-set vocabularies
	// (frame/target, node-state, message-sender-kind, subscription-scope, ...).
	for _, c := range dpkg.Consts {
		e := buildUntypedEnum(c)
		if e != nil {
			m.Enums = append(m.Enums, e)
		}
	}
}

// typeSpecOf extracts the single TypeSpec from a doc.Type's declaration.
func typeSpecOf(t *doc.Type) *ast.TypeSpec {
	if t.Decl == nil {
		return nil
	}
	for _, spec := range t.Decl.Specs {
		if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.Name == t.Name {
			return ts
		}
	}
	return nil
}

// buildStruct turns an *ast.StructType into a specStruct, resolving each
// field's YAML key, readable type, and doc.
func buildStruct(m *specModel, name, docText string, st *ast.StructType, fset *token.FileSet) *specStruct {
	s := &specStruct{Name: name, Doc: docText}
	if st.Fields == nil {
		return s
	}
	for _, f := range st.Fields.List {
		// Skip unexported fields; embedded fields are rendered via their tag if
		// present, otherwise by type name.
		fieldNames := f.Names
		if len(fieldNames) == 0 {
			// Embedded field — render by type name as the Go field identity.
			s.Fields = append(s.Fields, fieldFromTag(m, embeddedName(f.Type), renderType(fset, f.Type), f.Tag, fieldDoc(f)))
			continue
		}
		for _, n := range fieldNames {
			if !ast.IsExported(n.Name) {
				continue
			}
			s.Fields = append(s.Fields, fieldFromTag(m, n.Name, renderType(fset, f.Type), f.Tag, fieldDoc(f)))
		}
	}
	for _, f := range s.Fields {
		if f.Tagged {
			s.Tagged = true
			break
		}
	}
	return s
}

// fieldFromTag resolves the YAML key (yaml: → json: → lowercased field name)
// and the omitempty/inline modifiers from a field's struct tag.
func fieldFromTag(m *specModel, fieldName, goType string, tag *ast.BasicLit, docText string) specField {
	sf := specField{GoField: fieldName, GoType: goType, Doc: docText}
	yamlName, yamlOpts := tagValue(tag, "yaml")
	jsonName, jsonOpts := tagValue(tag, "json")

	var opts []string
	switch {
	case yamlName != "" || hasTag(tag, "yaml"):
		sf.YAMLKey = yamlName
		opts = yamlOpts
		sf.Tagged = true
	case jsonName != "" || hasTag(tag, "json"):
		sf.YAMLKey = jsonName
		opts = jsonOpts
		sf.Tagged = true
	}
	if sf.YAMLKey == "" {
		sf.YAMLKey = strings.ToLower(fieldName)
	}
	for _, o := range opts {
		switch o {
		case "omitempty":
			sf.OmitEmpty = true
		case "inline":
			sf.Inline = true
		}
	}
	return sf
}

// fieldDoc returns a field's doc comment: the leading doc block if present,
// else the trailing line comment.
func fieldDoc(f *ast.Field) string {
	if f.Doc != nil {
		return strings.TrimSpace(f.Doc.Text())
	}
	if f.Comment != nil {
		return strings.TrimSpace(f.Comment.Text())
	}
	return ""
}

// embeddedName returns the field name for an embedded (anonymous) field.
func embeddedName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	}
	return ""
}

// buildTypedEnum builds an enum from a named string type plus its const group.
func buildTypedEnum(t *doc.Type) *specEnum {
	e := &specEnum{Name: t.Name, GoType: "string", Typed: true, Doc: strings.TrimSpace(t.Doc)}
	for _, c := range t.Consts {
		e.Values = append(e.Values, constValues(c)...)
	}
	return e
}

// buildUntypedEnum builds an enum group from a standalone const block whose
// constants have no named type (the bare string vocabularies). Returns nil if
// the group has no exported string-literal constants.
func buildUntypedEnum(c *doc.Value) *specEnum {
	// A doc.Value with a non-empty type indicates a typed group already
	// covered by buildTypedEnum; skip those here.
	if constGroupHasNamedType(c) {
		return nil
	}
	vals := constValues(c)
	if len(vals) == 0 {
		return nil
	}
	e := &specEnum{Name: groupTitle(vals), Typed: false, Doc: strings.TrimSpace(c.Doc), Values: vals}
	return e
}

// constGroupHasNamedType reports whether any ValueSpec in the group declares a
// named (non-builtin) type — i.e. it is a typed enum group.
func constGroupHasNamedType(c *doc.Value) bool {
	if c.Decl == nil {
		return false
	}
	for _, spec := range c.Decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok || vs.Type == nil {
			continue
		}
		if id, ok := vs.Type.(*ast.Ident); ok {
			switch id.Name {
			case "string", "int", "int64", "bool", "float64":
				// builtin — still an untyped-for-our-purposes group
			default:
				return true
			}
		}
	}
	return false
}

// constValues extracts the exported string-literal constants from a const
// group, with per-const doc comments.
func constValues(c *doc.Value) []enumValue {
	var out []enumValue
	if c.Decl == nil {
		return out
	}
	for _, spec := range c.Decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for i, name := range vs.Names {
			if !ast.IsExported(name.Name) {
				continue
			}
			ev := enumValue{Name: name.Name}
			if vs.Doc != nil {
				ev.Doc = strings.TrimSpace(vs.Doc.Text())
			} else if vs.Comment != nil {
				ev.Doc = strings.TrimSpace(vs.Comment.Text())
			}
			if i < len(vs.Values) {
				ev.Value = stringLiteral(vs.Values[i])
			}
			// Only keep string-literal consts; numeric / duration consts are
			// not part of the YAML enum vocabulary.
			if ev.Value == "" {
				continue
			}
			out = append(out, ev)
		}
	}
	return out
}

// stringLiteral returns the unquoted value of a string-literal expression, or
// the empty string when expr is not a plain string literal. Conversions like
// `ClaimLifetime("subgraph")` and typed literals (`Severity = "error"`) both
// resolve to the inner string.
func stringLiteral(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind == token.STRING {
			return strings.Trim(e.Value, "`\"")
		}
	case *ast.CallExpr:
		// e.g. ClaimLifetime("subgraph")
		if len(e.Args) == 1 {
			return stringLiteral(e.Args[0])
		}
	}
	return ""
}
