// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// generate.go — captures the `rimsky` CLI's own help output and assembles it
// into a single markdown reference. The CLI's help is the source of truth: this
// tool reproduces it verbatim (inside fenced blocks) so an agent can read the
// entire command tree without inferring it.
//
// Capture is split from assembly: captureHelp() does the slow `go run`
// shelling-out against the rimsky checkout; assemble() is a pure function over
// the captured strings, so the markdown layout is unit-testable on a sample
// without invoking the CLI.
package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/rimsky-ai/rimsky-docs/cmd/internal/refpin"
)

const autogenBanner = "<!-- AUTOGENERATED by rimsky-docs-cli-ref from the rimsky CLI's own `help` output. Do not hand-edit. -->"

// perInvocationTimeout bounds each `go run ./cmd/rimsky ...` call. `go run` is
// slow (it compiles the CLI on first use, then runs it), so this is generous.
const perInvocationTimeout = 3 * time.Minute

// commandGroups is the fixed, sorted set of command groups documented one
// section apiece. A bare invocation of each (`rimsky <group>`) prints that
// group's usage. The list is kept sorted so iteration order — and therefore the
// generated output and `-check` — is deterministic. It mirrors the "Literal
// API" groups plus the standalone verbs that carry their own usage/flag help.
var commandGroups = []string{
	"admin",
	"agent",
	"asset",
	"backfill",
	"conformance",
	"ctx",
	"health",
	"instance",
	"lineage",
	"messages",
	"node",
	"parked",
	"run",
	"tag",
	"template",
	"version",
}

// capture is the captured help text for the CLI: the top-level tree plus one
// usage blob per command group.
type capture struct {
	topLevel string
	groups   []groupHelp
}

type groupHelp struct {
	name string
	help string
}

// run captures the CLI help and writes (or, with check, verifies) the reference
// at outPath.
func run(rimskyRepo, outPath, version string, check bool) error {
	cap, err := captureHelp(rimskyRepo)
	if err != nil {
		return err
	}
	md := assemble(cap, version)
	return writeOrCheck(md, outPath, check)
}

// writeOrCheck writes md to outPath, or — with check — compares md against
// what is on disk and returns an error on drift.
func writeOrCheck(md, outPath string, check bool) error {
	if check {
		want, err := os.ReadFile(outPath)
		if err != nil || !bytes.Equal([]byte(md), want) {
			return fmt.Errorf("CLI reference is out of date for:\n  %s\nrun `go run ./cmd/rimsky-docs-cli-ref` to regenerate", outPath)
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(md), 0644)
}

// captureHelp shells out to the rimsky CLI in rimskyRepo to capture the
// top-level command tree and each command group's usage. It is robust to
// non-zero exits (a bare group invocation exits non-zero while still printing
// usage), capturing combined stdout+stderr and treating the text as the
// payload. Group order follows the sorted commandGroups slice for determinism.
func captureHelp(rimskyRepo string) (capture, error) {
	top, err := runCLI(rimskyRepo, "help")
	if err != nil {
		// `help` exits 0, so a transport/compile failure here is fatal: without
		// the top-level tree there is nothing to anchor the reference.
		return capture{}, fmt.Errorf("capture top-level help (`go run ./cmd/rimsky help` in %s): %w", rimskyRepo, err)
	}

	groups := append([]string(nil), commandGroups...)
	sort.Strings(groups)

	cap := capture{topLevel: top}
	for _, g := range groups {
		// Prefer `<group> -h`: dispatch groups intercept it to print their
		// usage (exit 0), and leaf flag-verbs (`health`, `run`) print
		// deterministic flag help — crucially, `-h` short-circuits before any
		// network call, so `health -h` documents its flags instead of emitting
		// a non-deterministic "connection refused" from a live request. Both
		// stdout and stderr are captured and the trailing `go run`
		// "exit status N" line is stripped, so a non-zero exit is not fatal.
		help, _ := runCLI(rimskyRepo, g, "-h")
		if !looksLikeUsage(help) {
			// Fall back to the bare invocation, which most groups answer with
			// their usage line printed to stderr.
			if bare, _ := runCLI(rimskyRepo, g); looksLikeUsage(bare) || strings.TrimSpace(bare) != "" {
				help = bare
			}
		}
		cap.groups = append(cap.groups, groupHelp{name: g, help: help})
	}
	return cap, nil
}

// looksLikeUsage reports whether captured text resembles CLI usage/help rather
// than a runtime error or an empty result. Used to decide whether to fall back
// from `<group> -h` to a bare invocation.
func looksLikeUsage(s string) bool {
	t := strings.TrimSpace(s)
	if t == "" {
		return false
	}
	lower := strings.ToLower(t)
	return strings.HasPrefix(lower, "usage:") ||
		strings.HasPrefix(lower, "usage of ") ||
		strings.Contains(lower, "\nusage")
}

// runCLI runs `go run ./cmd/rimsky <args...>` with cmd.Dir set to the rimsky
// checkout, captures combined stdout+stderr, and strips the trailing
// "exit status N" line that `go run` appends when the program exits non-zero.
// It returns the cleaned text plus any execution error (a non-zero CLI exit is
// surfaced as err, but the text is still returned for the caller to use).
func runCLI(rimskyRepo string, args ...string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), perInvocationTimeout)
	defer cancel()

	full := append([]string{"run", "./cmd/rimsky"}, args...)
	cmd := exec.CommandContext(ctx, "go", full...)
	cmd.Dir = rimskyRepo
	out, err := cmd.CombinedOutput()
	return stripGoRunExit(string(out)), err
}

// stripGoRunExit removes the "exit status N" line `go run` appends to a
// non-zero subprocess's combined output, and trims surrounding blank lines.
func stripGoRunExit(s string) string {
	lines := strings.Split(s, "\n")
	for len(lines) > 0 {
		last := strings.TrimSpace(lines[len(lines)-1])
		if last == "" {
			lines = lines[:len(lines)-1]
			continue
		}
		if strings.HasPrefix(last, "exit status ") {
			lines = lines[:len(lines)-1]
			continue
		}
		break
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n")
}

// assemble renders the captured help into the full markdown reference. It is a
// pure function of the capture so the layout can be tested without invoking the
// CLI.
func assemble(cap capture, version string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n%s\n\n", autogenBanner, refpin.Banner(version))
	fmt.Fprintf(&b, "# rimsky CLI reference\n\n")
	fmt.Fprintf(&b, "The `rimsky` CLI is the human- and scripting-facing front-end to the REST "+
		"control API. It honors `RIMSKY_CONTROL_API` for the control-api endpoint "+
		"(or `--endpoint <url>`, or a configured context via `rimsky ctx use`). This "+
		"page reproduces the CLI's own `--help` output verbatim — the help text is "+
		"the authoritative description of every command — so the whole command tree "+
		"is readable here without invoking the binary.\n\n")
	fmt.Fprintf(&b, "## Command tree\n\n")
	fmt.Fprintf(&b, "`rimsky help` (the top-level usage):\n\n")
	fmt.Fprintf(&b, "```text\n%s\n```\n\n", strings.TrimRight(cap.topLevel, "\n"))

	fmt.Fprintf(&b, "## Command groups\n\n")
	fmt.Fprintf(&b, "One section per command group, each reproducing that group's usage "+
		"(`rimsky <group>`).\n\n")
	for _, g := range cap.groups {
		fmt.Fprintf(&b, "### `rimsky %s`\n\n", g.name)
		help := strings.TrimRight(g.help, "\n")
		if strings.TrimSpace(help) == "" {
			fmt.Fprintf(&b, "_No usage text captured for this group._\n\n")
			continue
		}
		fmt.Fprintf(&b, "```text\n%s\n```\n\n", help)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}
