// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const autogenWarning = "<!-- AUTOGENERATED from docs/concepts/. Do not edit by hand. Run `make docs-glossary`. -->\n"

func generate(conceptsDir string) ([]byte, error) {
	entries, err := os.ReadDir(conceptsDir)
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	var fms []*Frontmatter
	deprecatedTermsByCurrent := map[string][]string{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || e.Name() == "README.md" {
			continue
		}
		fm, err := ParseFrontmatter(filepath.Join(conceptsDir, e.Name()))
		if err != nil {
			return nil, err
		}
		fms = append(fms, fm)
		deprecatedTermsByCurrent[fm.Concept] = append(deprecatedTermsByCurrent[fm.Concept], fm.DeprecatedTerms...)
	}
	sort.Slice(fms, func(i, j int) bool { return fms[i].Concept < fms[j].Concept })

	var b bytes.Buffer
	b.WriteString(autogenWarning)
	b.WriteString("\n# Rimsky public glossary\n\n")
	b.WriteString("Authoritative public-surface vocabulary, generated from `docs/concepts/`. ")
	b.WriteString("For deeper material on each entry, follow the link to the concept file.\n\n")

	b.WriteString("## Concepts\n\n")
	b.WriteString("| Concept | Definition |\n|---|---|\n")
	for _, fm := range fms {
		def := strings.TrimSpace(strings.ReplaceAll(fm.Definition, "\n", " "))
		// collapse internal whitespace
		def = strings.Join(strings.Fields(def), " ")
		link := fmt.Sprintf("[%s](concepts/%s.md)", fm.Concept, fm.Concept)
		b.WriteString(fmt.Sprintf("| %s | %s |\n", link, def))
	}
	b.WriteString("\n")

	// Layered senses inline section
	hasLayered := false
	for _, fm := range fms {
		if len(fm.LayerSenses) > 0 {
			hasLayered = true
			break
		}
	}
	if hasLayered {
		b.WriteString("## Layered senses\n\n")
		b.WriteString("Some terms have layered presentations across the four-layer model. ")
		b.WriteString("See [`concepts/four-layer-model.md`](concepts/four-layer-model.md).\n\n")
		for _, fm := range fms {
			if len(fm.LayerSenses) == 0 {
				continue
			}
			b.WriteString(fmt.Sprintf("### %s\n\n", fm.Concept))
			for _, ls := range fm.LayerSenses {
				b.WriteString(fmt.Sprintf("- **%s layer**: %s\n", ls.Layer, ls.Sense))
			}
			b.WriteString("\n")
		}
	}

	// Deprecated terms section
	hasDeprecated := false
	for _, terms := range deprecatedTermsByCurrent {
		if len(terms) > 0 {
			hasDeprecated = true
			break
		}
	}
	if hasDeprecated {
		b.WriteString("## Deprecated terms\n\n")
		b.WriteString("| Deprecated | Current |\n|---|---|\n")
		type entry struct{ deprecated, current string }
		var rows []entry
		for current, terms := range deprecatedTermsByCurrent {
			for _, term := range terms {
				rows = append(rows, entry{deprecated: term, current: current})
			}
		}
		sort.Slice(rows, func(i, j int) bool { return rows[i].deprecated < rows[j].deprecated })
		for _, r := range rows {
			// Each row of the deprecated table literally contains the
			// deprecated term — that's the table's purpose. Emit a per-row
			// vocabulary-lint-ignore comment on the line preceding so the
			// vocabulary lint accepts the listing.
			b.WriteString(fmt.Sprintf("<!-- vocabulary-lint-ignore: %s -->\n", r.deprecated))
			b.WriteString(fmt.Sprintf("| `%s` | [%s](concepts/%s.md) |\n", r.deprecated, r.current, r.current))
		}
		b.WriteString("\n")
	}

	return b.Bytes(), nil
}
