// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_FixtureProducesSortedOutput(t *testing.T) {
	got, err := generate("testdata/concepts")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	s := string(got)
	if !strings.HasPrefix(s, "<!-- AUTOGENERATED") {
		t.Errorf("missing autogen warning, got prefix %q", s[:60])
	}
	// example must appear before two (alphabetical)
	iEx := strings.Index(s, "[example]")
	iTwo := strings.Index(s, "[two]")
	if iEx < 0 || iTwo < 0 || iEx > iTwo {
		t.Errorf("expected example before two; iEx=%d iTwo=%d", iEx, iTwo)
	}
	// deprecated table includes legacy_two
	if !strings.Contains(s, "`legacy_two`") {
		t.Error("expected deprecated terms table to include legacy_two")
	}
}

func TestRun_CheckMode_DetectsDrift(t *testing.T) {
	tmp := t.TempDir()
	outPath := filepath.Join(tmp, "glossary.md")
	if err := os.WriteFile(outPath, []byte("stale content"), 0644); err != nil {
		t.Fatal(err)
	}
	err := run("testdata/concepts", outPath, true)
	if err == nil {
		t.Fatal("expected drift error, got nil")
	}
	if !strings.Contains(err.Error(), "differs from generator output") {
		t.Errorf("unexpected error: %v", err)
	}
}

func TestRun_WriteMode_ProducesByteEqualOutput(t *testing.T) {
	tmp := t.TempDir()
	outPath := filepath.Join(tmp, "glossary.md")
	if err := run("testdata/concepts", outPath, false); err != nil {
		t.Fatalf("run write: %v", err)
	}
	wrote, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := generate("testdata/concepts")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(wrote, generated) {
		t.Error("write-mode output does not byte-equal generator output")
	}
}
