// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// main.go — rimsky-docs-llms-full. Concatenates docs/concepts/*.md and
// docs/protocols/*.md (frontmatter stripped, body included) into
// docs/agents/llms-full.txt for single-pull retrieval. The repo-root
// llms-full.txt at the rimsky-docs root is a verbatim copy maintained by
// the same run via -root-output.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	rimskyRepo := os.Getenv("RIMSKY_REPO")
	if rimskyRepo == "" {
		fmt.Fprintln(os.Stderr, "rimsky-docs-llms-full: RIMSKY_REPO is unset.")
		fmt.Fprintln(os.Stderr, "Set RIMSKY_REPO to a local rimsky checkout path, e.g.:")
		fmt.Fprintln(os.Stderr, "  RIMSKY_REPO=$(pwd)/../rimsky go run ./cmd/rimsky-docs-llms-full")
		fmt.Fprintln(os.Stderr, "Required by the docs reconciliation gate to cross-check generated content against rimsky source.")
		os.Exit(2)
	}
	// Concept catalog lives in rimsky's `.ok-planner/design/concepts/`;
	// protocol guides live in this repo under `docs/protocols/`.
	defaultConcepts := rimskyRepo + "/.ok-planner/design/concepts"
	conceptsDir := flag.String("concepts-dir", defaultConcepts, "path to concept files (defaults to ${RIMSKY_REPO}/.ok-planner/design/concepts)")
	protocolsDir := flag.String("protocols-dir", "../rimsky/skills/rimsky/docs/protocols", "path to protocol guides (relative to cmd/ cwd)")
	outputFile := flag.String("output", "../rimsky/skills/rimsky/docs/agents/llms-full.txt", "path to write generated llms-full.txt (relative to cmd/ cwd)")
	rootOutputFile := flag.String("root-output", "../llms-full.txt", "path to write repo-root copy (empty to skip; relative to cmd/ cwd)")
	check := flag.Bool("check", false, "verify existing output matches generated; exit non-zero on diff")
	flag.Parse()
	if err := run(*conceptsDir, *protocolsDir, *outputFile, *rootOutputFile, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(conceptsDir, protocolsDir, outputPath, rootOutputPath string, check bool) error {
	got, err := generate(conceptsDir, protocolsDir)
	if err != nil {
		return err
	}
	if check {
		want, err := os.ReadFile(outputPath)
		if err != nil {
			return fmt.Errorf("%s: %w", outputPath, err)
		}
		if !bytes.Equal(got, want) {
			return fmt.Errorf("%s differs from generator output; run `go run ./cmd/rimsky-docs-llms-full` to regenerate", outputPath)
		}
		if rootOutputPath != "" {
			rootWant, err := os.ReadFile(rootOutputPath)
			if err != nil {
				return fmt.Errorf("%s: %w", rootOutputPath, err)
			}
			if !bytes.Equal(got, rootWant) {
				return fmt.Errorf("%s differs from generator output; run `go run ./cmd/rimsky-docs-llms-full` to regenerate", rootOutputPath)
			}
		}
		return nil
	}
	if err := os.WriteFile(outputPath, got, 0644); err != nil {
		return err
	}
	if rootOutputPath != "" {
		if err := os.WriteFile(rootOutputPath, got, 0644); err != nil {
			return err
		}
	}
	return nil
}

func generate(conceptsDir, protocolsDir string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("# Rimsky — full canonical content\n\n")
	b.WriteString("> Generated by rimsky-docs-llms-full. For agents whose tooling can fetch ")
	b.WriteString("a single file but not crawl. Source of truth is `docs/concepts/` and `docs/protocols/`.\n\n")

	b.WriteString("---\n\n# Concepts\n\n")
	if err := concatBodies(&b, conceptsDir); err != nil {
		return nil, err
	}
	b.WriteString("---\n\n# Protocols\n\n")
	if err := concatBodies(&b, protocolsDir); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func concatBodies(b *bytes.Buffer, dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || e.Name() == "README.md" {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	for _, name := range names {
		raw, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return err
		}
		body := stripFrontmatter(raw)
		b.Write(body)
		b.WriteString("\n\n---\n\n")
	}
	return nil
}

func stripFrontmatter(raw []byte) []byte {
	if !bytes.HasPrefix(raw, []byte("---\n")) {
		return raw
	}
	end := bytes.Index(raw[4:], []byte("\n---\n"))
	if end < 0 {
		return raw
	}
	return bytes.TrimLeft(raw[4+end+5:], "\n")
}
