// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// generate.go — walks the protocols module's hand-written Go packages, parses
// each with go/parser, and renders its exported surface with go/doc. The
// proto/ subtree (generated protobuf bindings) is skipped; that wire reference
// is owned by rimsky-docs-proto. Stdlib only; no new dependencies.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rimsky-ai/rimsky-docs/cmd/internal/refpin"
)

const autogenBanner = "<!-- AUTOGENERATED by rimsky-docs-gopkg from rimsky lib/protocols/. Do not hand-edit. -->"

// run renders the Go package reference for protocolsDir to outPath. With
// check=true, compare against disk and error on drift.
func run(protocolsDir, outPath, version string, check bool) error {
	md, err := renderReference(protocolsDir, version)
	if err != nil {
		return err
	}

	if check {
		want, err := os.ReadFile(outPath)
		if err != nil || !bytes.Equal([]byte(md), want) {
			return fmt.Errorf("Go package reference is out of date for:\n  %s\nrun `go run ./cmd/rimsky-docs-gopkg` to regenerate", outPath)
		}
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(md), 0644)
}

// renderReference builds the full markdown doc for every hand-written package
// under protocolsDir (the proto/ subtree is excluded).
func renderReference(protocolsDir, version string) (string, error) {
	pkgDirs, err := packageDirs(protocolsDir)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n%s\n\n", autogenBanner, refpin.Banner(version))
	fmt.Fprintf(&b, "# rimsky protocols module — Go package reference\n\n")
	fmt.Fprintf(&b, "rimsky's `protocols` module is the single public Go module a service "+
		"implementer imports. It carries the wire contract and a few optional "+
		"helper packages — you can implement against the contract directly and "+
		"ignore the helpers entirely. This page is the generated reference for the "+
		"module's hand-written Go packages; the wire types themselves are "+
		"documented under [`reference/`](reference/). One section per package.\n\n")

	for _, dir := range pkgDirs {
		section, err := renderPackage(protocolsDir, dir)
		if err != nil {
			return "", err
		}
		b.WriteString(section)
	}
	return b.String(), nil
}

// packageDirs returns directories under protocolsDir that contain at least one
// non-_test .go file, sorted by import-path-relative name. The proto/ subtree
// (generated protobuf bindings, documented by rimsky-docs-proto) is excluded.
func packageDirs(protocolsDir string) ([]string, error) {
	seen := map[string]bool{}
	err := filepath.WalkDir(protocolsDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "proto" {
				return filepath.SkipDir
			}
			return nil
		}
		name := d.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		seen[filepath.Dir(path)] = true
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("%s: %w", protocolsDir, err)
	}
	dirs := make([]string, 0, len(seen))
	for d := range seen {
		dirs = append(dirs, d)
	}
	sort.Slice(dirs, func(i, j int) bool {
		return relImportPath(protocolsDir, dirs[i]) < relImportPath(protocolsDir, dirs[j])
	})
	return dirs, nil
}

// relImportPath returns the package's path relative to protocolsDir (".",
// "serverkit", "conformance/executor", ...).
func relImportPath(protocolsDir, dir string) string {
	rel, err := filepath.Rel(protocolsDir, dir)
	if err != nil {
		return dir
	}
	return filepath.ToSlash(rel)
}

// renderPackage parses one directory and renders its exported surface. Returns
// an empty string for packages with no exported symbols.
func renderPackage(protocolsDir, dir string) (string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parse %s: %w", dir, err)
	}

	rel := relImportPath(protocolsDir, dir)
	var b strings.Builder
	for _, pkg := range pkgs {
		dpkg := doc.New(pkg, rel, 0)
		if !hasExported(dpkg) {
			continue
		}
		renderDocPackage(&b, fset, rel, dpkg)
	}
	return b.String(), nil
}

func hasExported(d *doc.Package) bool {
	return len(d.Types) > 0 || len(d.Funcs) > 0 || len(d.Consts) > 0 || len(d.Vars) > 0
}

func renderDocPackage(b *strings.Builder, fset *token.FileSet, rel string, d *doc.Package) {
	fmt.Fprintf(b, "## %s\n\n", rel)
	fmt.Fprintf(b, "Package `%s`\n\n", d.Name)
	if d.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(d.Doc))
	}

	if len(d.Consts) > 0 {
		fmt.Fprintf(b, "### Constants\n\n")
		for _, c := range d.Consts {
			renderValue(b, fset, c)
		}
	}
	if len(d.Vars) > 0 {
		fmt.Fprintf(b, "### Variables\n\n")
		for _, v := range d.Vars {
			renderValue(b, fset, v)
		}
	}
	for _, t := range d.Types {
		fmt.Fprintf(b, "### type %s\n\n", t.Name)
		fmt.Fprintf(b, "```go\n%s\n```\n\n", sourceOf(fset, t.Decl))
		if t.Doc != "" {
			fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(t.Doc))
		}
		for _, f := range t.Funcs { // constructors
			renderFunc(b, fset, f)
		}
		for _, m := range t.Methods {
			renderFunc(b, fset, m)
		}
	}
	if len(d.Funcs) > 0 {
		fmt.Fprintf(b, "### Functions\n\n")
		for _, f := range d.Funcs {
			renderFunc(b, fset, f)
		}
	}
}

func renderFunc(b *strings.Builder, fset *token.FileSet, f *doc.Func) {
	fmt.Fprintf(b, "#### `%s`\n\n", funcSignature(fset, f.Decl))
	if f.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(f.Doc))
	}
}

func renderValue(b *strings.Builder, fset *token.FileSet, v *doc.Value) {
	fmt.Fprintf(b, "```go\n%s\n```\n\n", sourceOf(fset, v.Decl))
	if v.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(v.Doc))
	}
}

// funcSignature renders a func/method declaration without its body, as a
// single inline line.
func funcSignature(fset *token.FileSet, decl *ast.FuncDecl) string {
	if decl == nil {
		return ""
	}
	stripped := *decl
	stripped.Body = nil
	stripped.Doc = nil
	sig := sourceOf(fset, &stripped)
	sig = strings.TrimSuffix(strings.TrimSpace(sig), "{")
	return strings.Join(strings.Fields(sig), " ")
}

// sourceOf renders an AST node back to Go source text.
func sourceOf(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 4}
	if err := cfg.Fprint(&buf, fset, node); err != nil {
		return ""
	}
	return strings.TrimSpace(buf.String())
}
