// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rimsky-ai/rimsky-docs/cmd/internal/refpin"
)

// TestReferenceParity_DetectsGeneratorFailure exercises the orchestration: with
// RIMSKY_REPO unset, every generator exits non-zero (it cannot reconcile), and
// reference-parity must aggregate that into one failure naming the generators.
// The all-pass path needs a real RIMSKY_REPO + protoc + a buildable rimsky tree,
// so it is covered by the integration gate (`rimsky-docs-lint reference-parity`
// against a checkout), not a hermetic unit test.
// TestCheckVersionBanners exercises the banner check against a synthetic tree:
// pages stamped with the reconciledAgainst banner pass; a page missing it (or
// carrying a stale version's banner) fails and is named in the error.
func TestCheckVersionBanners(t *testing.T) {
	root := t.TempDir()
	repoRoot := filepath.Join(root, "cmd")
	docsRoot := filepath.Join(root, "rimsky", "skills", "rimsky", "docs")
	for _, dir := range []string{
		repoRoot,
		filepath.Join(root, "rimsky", ".claude-plugin"),
		filepath.Join(docsRoot, "protocols", "reference"),
		filepath.Join(docsRoot, "reference"),
	} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "rimsky", ".claude-plugin", "plugin.json"),
		[]byte(`{"reconciledAgainst":"v0.8.0"}`), 0644); err != nil {
		t.Fatal(err)
	}
	banner := refpin.Banner("v0.8.0")
	pages := []string{
		filepath.Join(docsRoot, "protocols", "go-packages.md"),
		filepath.Join(docsRoot, "reference", "template-schema.md"),
		filepath.Join(docsRoot, "reference", "rest-api.md"),
		filepath.Join(docsRoot, "reference", "cli.md"),
		filepath.Join(docsRoot, "protocols", "reference", "executor-proto.md"),
	}
	for _, page := range pages {
		if err := os.WriteFile(page, []byte("<!-- AUTOGENERATED -->\n"+banner+"\n\n# x\n"), 0644); err != nil {
			t.Fatal(err)
		}
	}

	if err := checkVersionBanners(repoRoot); err != nil {
		t.Errorf("expected pass with banners present, got %v", err)
	}

	stale := filepath.Join(docsRoot, "reference", "cli.md")
	if err := os.WriteFile(stale, []byte("<!-- AUTOGENERATED -->\n"+refpin.Banner("v0.7.0")+"\n\n# x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	err := checkVersionBanners(repoRoot)
	if err == nil {
		t.Fatal("expected failure for a stale banner")
	}
	if !strings.Contains(err.Error(), "cli.md") {
		t.Errorf("expected the failing page named in the error, got %v", err)
	}
}

func TestReferenceParity_DetectsGeneratorFailure(t *testing.T) {
	moduleRoot := findModuleRoot(t)
	t.Setenv("RIMSKY_REPO", "")
	err := runReferenceParity([]string{"-repo-root=" + moduleRoot})
	if err == nil {
		t.Fatal("expected failure when the generators cannot reconcile")
	}
	if !strings.Contains(err.Error(), "rimsky-docs-") {
		t.Errorf("expected the failing generator(s) named in the error, got %v", err)
	}
}
