// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

// generate.go — the proto → markdown pipeline. Invokes protoc to get a
// FileDescriptorSet with source info, then renders one markdown file per
// proto into <outDir>/reference/.
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const autogenBanner = "<!-- AUTOGENERATED by rimsky-docs-proto from rimsky lib/protocols/proto/v1/. Do not hand-edit. -->"

// run drives the whole generation. When check is true it compares the
// regenerated markdown against what is on disk and returns an error on drift.
func run(protoDir, outDir string, check bool) error {
	fds, err := compileDescriptorSet(protoDir)
	if err != nil {
		return err
	}

	refDir := filepath.Join(outDir, "reference")
	if !check {
		if err := os.MkdirAll(refDir, 0755); err != nil {
			return err
		}
	}

	var drift []string
	for _, fdp := range fds.GetFile() {
		md := renderFile(fdp)
		name := hyphenate(fdp.GetName())
		outPath := filepath.Join(refDir, name+".md")
		if check {
			want, err := os.ReadFile(outPath)
			if err != nil {
				drift = append(drift, fmt.Sprintf("%s: %v", outPath, err))
				continue
			}
			if !bytes.Equal([]byte(md), want) {
				drift = append(drift, outPath)
			}
			continue
		}
		if err := os.WriteFile(outPath, []byte(md), 0644); err != nil {
			return err
		}
	}

	if check && len(drift) > 0 {
		return fmt.Errorf("proto reference is out of date for:\n  %s\nrun `go run ./cmd/rimsky-docs-proto` to regenerate", strings.Join(drift, "\n  "))
	}
	return nil
}

// compileDescriptorSet shells out to protoc to produce a FileDescriptorSet
// (with source info, so comments survive) for every .proto in protoDir.
func compileDescriptorSet(protoDir string) (*descriptorpb.FileDescriptorSet, error) {
	absProtoDir, err := filepath.Abs(protoDir)
	if err != nil {
		return nil, err
	}
	protoDir = absProtoDir
	entries, err := os.ReadDir(protoDir)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", protoDir, err)
	}
	var protoFiles []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".proto") {
			protoFiles = append(protoFiles, filepath.Join(protoDir, e.Name()))
		}
	}
	if len(protoFiles) == 0 {
		return nil, fmt.Errorf("no .proto files found in %s", protoDir)
	}
	sort.Strings(protoFiles)

	tmpDir, err := os.MkdirTemp("", "rimsky-docs-proto-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmpDir)
	descPath := filepath.Join(tmpDir, "descriptors.pb")

	args := []string{"-I", protoDir, "--include_source_info", "--descriptor_set_out=" + descPath}
	args = append(args, protoFiles...)
	cmd := exec.Command("protoc", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("protoc failed: %w\n%s", err, out)
	}

	raw, err := os.ReadFile(descPath)
	if err != nil {
		return nil, err
	}
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(raw, fds); err != nil {
		return nil, fmt.Errorf("unmarshal descriptor set: %w", err)
	}
	return fds, nil
}

// hyphenate maps a proto basename ("a/claim_producer.proto") to its doc slug
// ("claim-producer").
func hyphenate(protoPath string) string {
	base := filepath.Base(protoPath)
	base = strings.TrimSuffix(base, ".proto")
	return strings.ReplaceAll(base, "_", "-")
}

// titleize maps a proto basename to a human title ("Claim Producer").
func titleize(protoPath string) string {
	base := strings.TrimSuffix(filepath.Base(protoPath), ".proto")
	parts := strings.Split(base, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}

// commentIndex maps a SourceCodeInfo path (joined to a string key) to its
// leading comment text. Comments live in SourceCodeInfo.Location.
type commentIndex map[string]string

func buildCommentIndex(fdp *descriptorpb.FileDescriptorProto) commentIndex {
	idx := commentIndex{}
	for _, loc := range fdp.GetSourceCodeInfo().GetLocation() {
		c := strings.TrimSpace(loc.GetLeadingComments())
		if c == "" {
			continue
		}
		idx[pathKey(loc.GetPath())] = cleanComment(c)
	}
	return idx
}

func pathKey(path []int32) string {
	parts := make([]string, len(path))
	for i, p := range path {
		parts[i] = strconv.Itoa(int(p))
	}
	return strings.Join(parts, ".")
}

// cleanComment collapses a multi-line leading comment into a single markdown
// paragraph: trims the per-line leading space protoc preserves and joins
// hard-wrapped lines, keeping blank lines as paragraph breaks.
func cleanComment(c string) string {
	lines := strings.Split(c, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimSpace(l)
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

// inlineComment flattens a comment to one line for use inside a markdown table
// cell, escaping pipes so they do not break the column layout.
func inlineComment(c string) string {
	if c == "" {
		return ""
	}
	fields := strings.Fields(strings.ReplaceAll(c, "\n", " "))
	return strings.ReplaceAll(strings.Join(fields, " "), "|", "\\|")
}
